#!/bin/bash
#/etc/init.d/orch

if [ "$#" -eq 2 ]
	then
	notDaemonize=$2
	else
	notDaemonize="False"
fi

do_start() {
	PID=$(pgrep -f /opt/softway4iot/src/orch/app.py)

	if [ "$PID" != "" ]
	then
		echo "Orch already started!!!"
	else
		if [ $notDaemonize == "-i" ];
		then
			echo "Starting in interactive mode"
			sudo python3 
		else
			nohup sudo python3 /opt/softway4iot/src/orch/app.py > /dev/null &
		fi
		
		sleep 2
		PID=$(pgrep -f /opt/softway4iot/src/net-manager/app.py)
		echo "Orch started... Process id: ${PID}..."
	fi
}

do_stop() {
	PID=$(pgrep -f /opt/softway4iot/src/orch/app.py)

	if [ "$PID" != "" ]
	then
		do_force_stop
	else
		echo "Orch already stoped!!!"
	fi
}

do_force_stop() {
	PID=$(pgrep -f /opt/softway4iot/src/orch/app.py)

	kill -9 $PID

	sleep 2
	echo "Net-Manager stoped..."
}

do_restart() {
	PID=$(pgrep -f /opt/softway4iot/src/orch/app.py)

	if [ "$PID" != "" ]
	then
		do_force_stop
		do_start
	else
		do_start
	fi
}

do_force_restart() {
	do_force_stop
	do_start
}

do_status() {
	PID=$(pgrep -f /opt/softway4iot/src/orch/app.py)

	if [ "$PID" != "" ]
	then
		echo "Orch is running... Process id: $PID"
	else
		echo "Orch is not running!!!"
	fi
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	force-stop)
		do_force_stop
		;;
	restart)
		do_restart
		;;
	force-restart)
		do_force_restart
		;;
	status)
		do_status
		;;
	*)
		echo "*Usage: /etc/init.d/orch (start|stop|force-stop|restart|force-restart|status)"
		;;
esac
